name: Update Counter

on: 
  push:
    branches:
      - main

permissions:
  contents: write  # Grant write permission to push to the repo

jobs:
  update-counter:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Read and update counter
      run: |
        echo "Current count:"
        if [ ! -f loop_counter.txt ]; then
          echo 0 > loop_counter.txt
        fi
        count=$(cat loop_counter.txt)
        echo $count
        new_count=$((count+7))
        echo $new_count > loop_counter.txt
        cat loop_counter.txt

    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        git add loop_counter.txt
        git commit -m "Update counter to $new_count"
        git push
